# Exploring MAUDE Database

The data used in this analysis is from the Manufacturer and User Facility Device Experience (MAUDE) Database provided through the openFDA (https://open.fda.gov/).

The openFDA has datasets covering:
1. Pharmaceuticals
2. Medical Devices
3. Food

The datasets cover a large variety of information, such as:
- Adverse Events
- Labeling
- Registrations 
- Recalls
- Classification 

## MAUDE 

The purpose of this project is to dive into the Federal Food and Drug Administration's (FDA) Medical Device Adverse Event Database (MAUDE).  Medical devices range from band-aids to artificial hearts and x-ray imagers, and are regulated using a risk based approach.  An adverse event is any untoward medical condition that is associated with the medical device, or may be associated with the medical device. 

Manufacturer's a required to maintain and evaluated complaint, including potential adverse events, for their devices. In addition, MAUDE was developed by the FDA as an additional platform for reporting adverse events.  There is a limited amount of control in how thoroughly the adverse event is reported.  For that reason, there is a lot of missing data in this dataset.

The initial json request sent, for all medical device advese events between January 1, 2017 - December 31, 2017 returned a total count of 935708 adverse events.  For this reason, a subset of the data will be used for the initial analysis.

In [24]:
import pandas as pd 
import numpy as np 
import urllib.request, json
from pandas.io.json import json_normalize
import datetime

# Examining the Data

The initial form of the data is a JSON structured nested dictionary, which will require multiple iterations to flatten and maintain the desired information.  This will be done initially using the json_normalize function.  The beginning structure of the adverse event is:

<img src="openfda_json.png">

All of the information of interest is housed in "results."

## First Normalization

In [25]:
# Returning 100 adverse events in a json dictionary from the openFDA API  
with urllib.request.urlopen("https://api.fda.gov/device/event.json?search=date_received:[20170101+TO+20171231]&limit=100") as url:
    data = json.loads(url.read())

# Normalize the data based on the "results" section of the JSON
# First normalization to see the structure of the data
maude_general = json_normalize(data['results'])

maude_general.head()

,adverse_event_flag,date_facility_aware,date_manufacturer_received,date_of_event,date_received,date_report,device,device_date_of_manufacturer,distributor_address_1,distributor_address_2,...,removal_correction_number,report_number,report_source_code,report_to_fda,report_to_manufacturer,reporter_occupation_code,reprocessed_and_reused_flag,single_use_flag,source_type,type_of_report
0,Y,NaN,20110503,20100101,20170112,20110421,[],NaN,,,...,,1226230-2011-00002,Manufacturer report,N,,PHYSICIAN,I,Y,[HEALTH PROFESSIONAL],"[Followup, Followup, Followup, Followup, Follo..."
1,N,NaN,20150810,NaN,20170309,NaN,"[{'manufacturer_d_address_1': '', 'manufacture...",20030314,,,...,,2210968-2015-02964,Manufacturer report,N,,,I,*,[],[Followup]
2,N,NaN,20170802,20161205,20170101,20161229,[{'manufacturer_d_address_1': '900 WALNUT RIDG...,20150721,,,...,,2183926-2016-00829,Manufacturer report,N,,OTHER,N,N,[USER FACILITY],[Initial submission]
3,N,NaN,20170221,20161209,20170101,20161209,[{'manufacturer_d_address_1': '900 WALNUT RIDG...,20150721,,,...,,2183926-2016-00828,Manufacturer report,N,,OTHER,N,N,[USER FACILITY],[Initial submission]
4,N,NaN,20170928,20161208,20170101,20161208,[{'manufacturer_d_address_1': '900 WALNUT RIDG...,20150330,,,...,,2183926-2016-00830,Manufacturer report,N,,OTHER,N,N,[USER FACILITY],[Initial submission]

## Second Normalization

The second stage of normalization was done focusing on the nested dictionary "device", where the majority of the desired information is housed.  Additional information from "results" is appended to the flattened table as well for each adverse event. A lot of the columns from results were ignored, since previewing the data for another project demonstrated that those columns are empty >90% of the time.

In [26]:
# Most of the imformation is housed within the "device" section of the "results
maude_device = json_normalize(data=data['results'], record_path='device', 
        # Appending meta data to the end of each row with information we want to keep from "results"
        meta=['adverse_event_flag', 'date_manufacturer_received','date_of_event', 
        'event_key', 'event_location', 'event_type',
        'health_professional', 'manufacturer_city', 'manufacturer_country'],
        errors='ignore')

In [27]:
maude_device.head()

,brand_name,catalog_number,date_received,date_removed_flag,date_returned_to_manufacturer,device_age_text,device_availability,device_evaluated_by_manufacturer,device_event_key,device_operator,...,other_id_number,adverse_event_flag,date_manufacturer_received,date_of_event,event_key,event_location,event_type,health_professional,manufacturer_city,manufacturer_country
0,MESH,,20170309,,NaN,DA,Yes,N,,HEALTH PROFESSIONAL,...,,N,20150810,nan,,I,Injury,,,
1,MERGE HEMODYNAMICS,,20170101,,NaN,DA,Yes,R,,HEALTH PROFESSIONAL,...,,N,20170802,20161205,,I,Malfunction,N,,
2,MERGE HEMODYNAMICS,,20170101,,20170220,DA,Device was returned to manufacturer,Y,,HEALTH PROFESSIONAL,...,,N,20170221,20161209,,I,Malfunction,N,,
3,MERGE UNITY PACS,,20170101,,NaN,DA,Yes,Y,,HEALTH PROFESSIONAL,...,,N,20170928,20161208,,I,Malfunction,N,,
4,OT VERIO FLEX METER,,20170101,,NaN,,No,R,,LAY USER/PATIENT,...,1-3BBSA4F,N,20161224,nan,,I,Malfunction,N,,

## Final Flattening Step

Good information is housed within the "device" section, in a sub-dictionary called "openfda."  This contains the device classification, generic medical name and the medical specialty.

This was extracted using a function that takes the information from the dictionary and returns it in a list.  Then was applied to the dataframe, converted from a series of lists to a dataframe, and transposed.  Then it was added to the main dataset after conforming they are equal lengths.

In [28]:
# A function to extract the desired data from the openfda column
def get_openfda(open_dict):
    try:
        # The data is housed in a json dictionary structure
        device_name = open_dict['device_name']
        device_class = open_dict['device_class']
        medical_specialty = open_dict['medical_specialty_description']
    except:
        return [np.NaN, np.NaN, np.NaN]
    # returning all of the captured information
    return [device_name, device_class, medical_specialty]

In [29]:
# Creating a series containing all of the results using df.apply
openfda = maude_device['openfda'].apply(get_openfda)

# Converting the lists in the series to a dataframe
openfda_df = pd.DataFrame.from_items(zip(openfda.index, openfda.values))
openfda_df = openfda_df.transpose()
openfda_df.columns = ['general_device_name', 'device_class', 'medical_specialty']

C:\Users\Tierra\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: from_items is deprecated. Please use DataFrame.from_dict(dict(items), ...) instead. DataFrame.from_dict(OrderedDict(items)) may be used to preserve the key order.
  """

In [30]:
# Making sure the maude_device dataframe and the openfda_df dataframe are the same length before merging
print("The length of the dataframes are: {}".format([len(maude_device), len(openfda_df)]))

openfda_df.head()

The length of the dataframes are: [99, 99]

,general_device_name,device_class,medical_specialty
0,"Mesh, Surgical, Polymeric",2,"General, Plastic Surgery"
1,"Computer, Diagnostic, Programmable",2,Cardiovascular
2,"Computer, Diagnostic, Programmable",2,Cardiovascular
3,"System, Image Processing, Radiological",2,Radiology
4,"System, Test, Blood Glucose, Over The Counter",2,Clinical Chemistry

In [31]:
# Combinding the two dataframes
maude_tot = pd.concat([maude_device, openfda_df], axis=1)
# Removing the initial openfda column
maude_tot.drop('openfda', axis=1, inplace=True)
maude_tot.head()

,brand_name,catalog_number,date_received,date_removed_flag,date_returned_to_manufacturer,device_age_text,device_availability,device_evaluated_by_manufacturer,device_event_key,device_operator,...,date_of_event,event_key,event_location,event_type,health_professional,manufacturer_city,manufacturer_country,general_device_name,device_class,medical_specialty
0,MESH,,20170309,,NaN,DA,Yes,N,,HEALTH PROFESSIONAL,...,nan,,I,Injury,,,,"Mesh, Surgical, Polymeric",2,"General, Plastic Surgery"
1,MERGE HEMODYNAMICS,,20170101,,NaN,DA,Yes,R,,HEALTH PROFESSIONAL,...,20161205,,I,Malfunction,N,,,"Computer, Diagnostic, Programmable",2,Cardiovascular
2,MERGE HEMODYNAMICS,,20170101,,20170220,DA,Device was returned to manufacturer,Y,,HEALTH PROFESSIONAL,...,20161209,,I,Malfunction,N,,,"Computer, Diagnostic, Programmable",2,Cardiovascular
3,MERGE UNITY PACS,,20170101,,NaN,DA,Yes,Y,,HEALTH PROFESSIONAL,...,20161208,,I,Malfunction,N,,,"System, Image Processing, Radiological",2,Radiology
4,OT VERIO FLEX METER,,20170101,,NaN,,No,R,,LAY USER/PATIENT,...,nan,,I,Malfunction,N,,,"System, Test, Blood Glucose, Over The Counter",2,Clinical Chemistry

# Expanding the Dataset

Now that the data is flattened appropriately, the same methods for flattening can be applied to a larger dataset.  To avoid the slow down from sending a lot of incremented queries, since the openFDA API only returns a maximum of 100 items for each request, the data is also provided in JSON files.

In [32]:
def get_json(json_file):
    with open(json_file) as f:
        data = json.load(f)
    return data

def normalize_maude(data):
    # Normalize the data based on the "results" section of the JSON
    # First normalization to see the structure of the data
    maude_general = json_normalize(data['results'])
    
    # Most of the imformation is housed within the "device" section of the "results
    maude_device = json_normalize(data=data['results'], record_path='device', 
    # Appending meta data to the end of each row with information we want to keep from "results"
         meta=['adverse_event_flag', 'date_manufacturer_received','date_of_event', 
         'event_key', 'event_location', 'event_type',
         'health_professional', 'manufacturer_city', 'manufacturer_country'],
        errors='ignore')
    
    # Creating a series containing all of the results using df.apply
    openfda = maude_device['openfda'].apply(get_openfda)
    
    # Converting the lists in the series to a dataframe
    openfda_df = pd.DataFrame.from_items(zip(openfda.index, openfda.values))
    openfda_df = openfda_df.transpose()
    openfda_df.columns = ['general_device_name', 'device_class', 'medical_specialty']
    
    # Combinding the two dataframes
    maude_tot = pd.concat([maude_device, openfda_df], axis=1)
    # Removing the initial openfda column
    maude_tot.drop('openfda', axis=1, inplace=True)
    return maude_tot

In [33]:
# Importing part of the dataset for Q1 2017
data_2017_Q1_1 = get_json(r'C:\Users\Tierra\Documents\datasets\maude\maude2017_q1_1.json')
data_2017_Q1_2 = get_json(r'C:\Users\Tierra\Documents\datasets\maude\maude2017_q1_2.json')
data_2017_Q1_3 = get_json(r'C:\Users\Tierra\Documents\datasets\maude\maude2017_q1_3.json')

In [35]:
# Flattening all of the datasets
flat_2017_Q1_1 = normalize_maude(data_2017_Q1_1)
flat_2017_Q1_2 = normalize_maude(data_2017_Q1_1)
flat_2017_Q1_3 = normalize_maude(data_2017_Q1_1)
flat_2017_Q1_1.head()

C:\Users\Tierra\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: from_items is deprecated. Please use DataFrame.from_dict(dict(items), ...) instead. DataFrame.from_dict(OrderedDict(items)) may be used to preserve the key order.

,brand_name,catalog_number,date_received,date_removed_flag,date_returned_to_manufacturer,device_age_text,device_availability,device_evaluated_by_manufacturer,device_event_key,device_operator,...,date_of_event,event_key,event_location,event_type,health_professional,manufacturer_city,manufacturer_country,general_device_name,device_class,medical_specialty
0,"LIBERTY CYCLER SET, SINGLE CONN./EXT. DL",050-87216,20170125,,NaN,MO,No,R,,LAY USER/PATIENT,...,20161229,,I,Malfunction,N,,,"System, Peritoneal, Automatic Delivery",2,"Gastroenterology, Urology"
1,FINESSIS ZERO CHEMO FLEXYLON POWDER FREE,,20170308,,NaN,,No,I,,HEALTH PROFESSIONAL,...,20170301,,NO INFORMATION,Injury,*,,,Surgeon'S Gloves,1,"General, Plastic Surgery"
2,TRILOGY 100,1054260,20170110,,20161227,,Device was returned to manufacturer,Y,,HEALTH PROFESSIONAL,...,20161123,,I,Death,Y,,,"Ventilator, Continuous, Facility Use",2,Anesthesiology
3,CONTOUR NEXT,,20170201,,20170210,DA,Device was returned to manufacturer,Y,,LAY USER/PATIENT,...,20170108,,I,Injury,N,,,"System, Test, Blood Glucose, Over The Counter",2,Clinical Chemistry
4,OT VERIO IQ METER,,20170209,,NaN,,No,R,,LAY USER/PATIENT,...,nan,,I,Malfunction,N,,,"System, Test, Blood Glucose, Over The Counter",2,Clinical Chemistry

## Exploring the data

In [37]:
flat_2017 = pd.concat([flat_2017_Q1_1, flat_2017_Q1_2, flat_2017_Q1_3], axis=0)
print("The number of adverse events in the dataset: {}".format(flat_2017.shape[0]))
flat_2017.info()

The number of adverse events in the dataset: 302808
<class 'pandas.core.frame.DataFrame'>
Int64Index: 302808 entries, 0 to 100935
Data columns (total 39 columns):
brand_name                          302808 non-null object
catalog_number                      302808 non-null object
date_received                       302808 non-null object
date_removed_flag                   302808 non-null object
date_returned_to_manufacturer       105054 non-null object
device_age_text                     302808 non-null object
device_availability                 302808 non-null object
device_evaluated_by_manufacturer    302808 non-null object
device_event_key                    302808 non-null object
device_operator                     302808 non-null object
device_report_product_code          302808 non-null object
device_sequence_number              302808 non-null object
expiration_date_of_device           71511 non-null object
generic_name                        302808 non-null object
implant_flag                        302808 non-null object
lot_number                          302808 non-null object
manufacturer_d_address_1            302808 non-null object
manufacturer_d_address_2            302808 non-null object
manufacturer_d_city                 302808 non-null object
manufacturer_d_country              302808 non-null object
manufacturer_d_name                 302808 non-null object
manufacturer_d_postal_code          302808 non-null object
manufacturer_d_state                302808 non-null object
manufacturer_d_zip_code             302808 non-null object
manufacturer_d_zip_code_ext         302808 non-null object
model_number                        302808 non-null object
other_id_number                     302808 non-null object
adverse_event_flag                  302808 non-null object
date_manufacturer_received          302808 non-null object
date_of_event                       302808 non-null object
event_key                           302808 non-null object
event_location                      302808 non-null object
event_type                          302808 non-null object
health_professional                 302808 non-null object
manufacturer_city                   302808 non-null object
manufacturer_country                302808 non-null object
general_device_name                 302328 non-null object
device_class                        302328 non-null object
medical_specialty                   302328 non-null object
dtypes: object(39)
memory usage: 92.4+ MB

It appears there's not a lot of null values in our dataset, but on visual inspection there is clearly a lot of blank columns.  To get a better idea of how much data is missing, the missing data will be replaced with null values.

## Data Cleaning

In [38]:
# Replacing missing data with null values
flat_2017 = flat_2017.replace({'': np.NaN, 'nan': np.NaN, 'NaN': np.NaN})
# Looking at the number of null values in each column
flat_null = flat_2017.isnull().sum()
flat_null

brand_name                            2163
catalog_number                      101388
date_received                            0
date_removed_flag                   302808
date_returned_to_manufacturer       197754
device_age_text                     154251
device_availability                      6
device_evaluated_by_manufacturer         9
device_event_key                    302808
device_operator                          6
device_report_product_code               0
device_sequence_number                   0
expiration_date_of_device           231297
generic_name                          1758
implant_flag                        302808
lot_number                          140910
manufacturer_d_address_1             17160
manufacturer_d_address_2            252705
manufacturer_d_city                   7059
manufacturer_d_country               21681
manufacturer_d_name                    849
manufacturer_d_postal_code           29511
manufacturer_d_state                 79146
manufacturer_d_zip_code              29511
manufacturer_d_zip_code_ext         241269
model_number                         94422
other_id_number                     223188
adverse_event_flag                    2556
date_manufacturer_received            8664
date_of_event                        78171
event_key                           302808
event_location                           0
event_type                               0
health_professional                  18285
manufacturer_city                   302808
manufacturer_country                302808
general_device_name                    480
device_class                           480
medical_specialty                      480
dtype: int64

In [39]:
# Filtering out columns that are missing more than 30% of the data
null_33 = flat_null[flat_null<(len(flat_2017)/3)].index
flat_less_null = flat_2017[null_33].copy()
flat_less_null.head()

,brand_name,date_received,device_availability,device_evaluated_by_manufacturer,device_operator,device_report_product_code,device_sequence_number,generic_name,manufacturer_d_address_1,manufacturer_d_city,...,model_number,adverse_event_flag,date_manufacturer_received,date_of_event,event_location,event_type,health_professional,general_device_name,device_class,medical_specialty
0,"LIBERTY CYCLER SET, SINGLE CONN./EXT. DL",20170125,No,R,LAY USER/PATIENT,FKX,1.0,"SYSTEM, PERITONEAL, AUTOMATED DELIVERY",MIKE ALLEN #1331,REYNOSA,...,NaN,N,20170126,20161229,I,Malfunction,N,"System, Peritoneal, Automatic Delivery",2,"Gastroenterology, Urology"
1,FINESSIS ZERO CHEMO FLEXYLON POWDER FREE,20170308,No,I,HEALTH PROFESSIONAL,KGO,1.0,FLEXYLON SURGICAL GLOVE,NaN,BAAR,...,FINESSIS ZERO CHEMO FLEXYLON,N,NaN,20170301,NO INFORMATION,Injury,*,Surgeon'S Gloves,1,"General, Plastic Surgery"
2,TRILOGY 100,20170110,Device was returned to manufacturer,Y,HEALTH PROFESSIONAL,CBK,1.0,"VENTILATOR, CONTINUOUS, FACILITY USE",1001 MURRY RIDGE LANE,MURRYSVILLE,...,1054260,Y,20161212,20161123,I,Death,Y,"Ventilator, Continuous, Facility Use",2,Anesthesiology
3,CONTOUR NEXT,20170201,Device was returned to manufacturer,Y,LAY USER/PATIENT,NBW,1.0,BLOOD GLUCOSE TEST STRIPS,430 S. BEIGER ST.,MISHAWAKA,...,7312,Y,20170210,20170108,I,Injury,N,"System, Test, Blood Glucose, Over The Counter",2,Clinical Chemistry
4,OT VERIO IQ METER,20170209,No,R,LAY USER/PATIENT,NBW,1.0,GLUCOSE MONITORING SYS/KIT,GUBELSTRASSE 34,ZUG,...,NaN,N,20170201,NaN,I,Malfunction,N,"System, Test, Blood Glucose, Over The Counter",2,Clinical Chemistry

Prior to dropping the rows containing NaN values, a few more columns that probably don't hold useful information for analysis will be dropped.  In addition repeatative columns, such as multiple instances of the manufacturer's location will be dropped or postal code and zip code.

In [40]:
flat_less_null.columns

Index(['brand_name', 'date_received', 'device_availability',
       'device_evaluated_by_manufacturer', 'device_operator',
       'device_report_product_code', 'device_sequence_number', 'generic_name',
       'manufacturer_d_address_1', 'manufacturer_d_city',
       'manufacturer_d_country', 'manufacturer_d_name',
       'manufacturer_d_postal_code', 'manufacturer_d_state',
       'manufacturer_d_zip_code', 'model_number', 'adverse_event_flag',
       'date_manufacturer_received', 'date_of_event', 'event_location',
       'event_type', 'health_professional', 'general_device_name',
       'device_class', 'medical_specialty'],
      dtype='object')

In [41]:
# Dropping redundant or non relevant columns
not_relevant = ['manufacturer_d_address_1','manufacturer_d_postal_code']

flat_less_null.drop(not_relevant, inplace=True, axis=1)
flat_less_null.head()

,brand_name,date_received,device_availability,device_evaluated_by_manufacturer,device_operator,device_report_product_code,device_sequence_number,generic_name,manufacturer_d_city,manufacturer_d_country,...,model_number,adverse_event_flag,date_manufacturer_received,date_of_event,event_location,event_type,health_professional,general_device_name,device_class,medical_specialty
0,"LIBERTY CYCLER SET, SINGLE CONN./EXT. DL",20170125,No,R,LAY USER/PATIENT,FKX,1.0,"SYSTEM, PERITONEAL, AUTOMATED DELIVERY",REYNOSA,MX,...,NaN,N,20170126,20161229,I,Malfunction,N,"System, Peritoneal, Automatic Delivery",2,"Gastroenterology, Urology"
1,FINESSIS ZERO CHEMO FLEXYLON POWDER FREE,20170308,No,I,HEALTH PROFESSIONAL,KGO,1.0,FLEXYLON SURGICAL GLOVE,BAAR,NaN,...,FINESSIS ZERO CHEMO FLEXYLON,N,NaN,20170301,NO INFORMATION,Injury,*,Surgeon'S Gloves,1,"General, Plastic Surgery"
2,TRILOGY 100,20170110,Device was returned to manufacturer,Y,HEALTH PROFESSIONAL,CBK,1.0,"VENTILATOR, CONTINUOUS, FACILITY USE",MURRYSVILLE,US,...,1054260,Y,20161212,20161123,I,Death,Y,"Ventilator, Continuous, Facility Use",2,Anesthesiology
3,CONTOUR NEXT,20170201,Device was returned to manufacturer,Y,LAY USER/PATIENT,NBW,1.0,BLOOD GLUCOSE TEST STRIPS,MISHAWAKA,US,...,7312,Y,20170210,20170108,I,Injury,N,"System, Test, Blood Glucose, Over The Counter",2,Clinical Chemistry
4,OT VERIO IQ METER,20170209,No,R,LAY USER/PATIENT,NBW,1.0,GLUCOSE MONITORING SYS/KIT,ZUG,SZ,...,NaN,N,20170201,NaN,I,Malfunction,N,"System, Test, Blood Glucose, Over The Counter",2,Clinical Chemistry

In [42]:
maude_final = flat_less_null.dropna().copy()
print("Remaining datapoints: {}".format(maude_final.shape[0]))

Remaining datapoints: 144594

The next step will be to convert all of the dates to datetime objects.

In [43]:
# Selecting all columns that contain date
date_columns = maude_final.columns[maude_final.columns.str.contains('date')]

for col in date_columns:
    maude_final[col] = pd.to_datetime(maude_final[col], errors='coerce')
    
maude_final[date_columns].head()

   date_received date_manufacturer_received date_of_event
2     2017-01-10                 2016-12-12    2016-11-23
3     2017-02-01                 2017-02-10    2017-01-08
31    2017-01-05                 2016-12-15    2016-12-15
32    2017-01-05                 2016-12-13    2016-12-13
33    2017-01-06                 2016-12-14    2016-12-14

In [44]:
maude_final.to_csv(r'C:\Users\Tierra\Documents\datasets\maude\maude_2017_q1_cleaned.csv', index=False)